version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - task-network

volumes:
  mysql-data:

networks:
  task-network:
    driver: bridge
