version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - task-network

  nestapp:
    build: .
    container_name: task-manager-nest
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: task-manager-mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: userpassword
      DB_NAME: task_manager
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - task-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql-data:

networks:
  task-network:
    driver: bridge
